CONFIG_ZMK_DISPLAY=y
CONFIG_NICE_VIEW_WIDGET_STATUS=n # don't compile ZMK's nice!view display code
# this way we can still use ZMK's `nice_view` shield for the hardware definitions only

CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=4096
